#?? ??? ?????? ??? ???? ??
#????? ??? ??? ??
#yml -> ???? : ?
#?? ???? ???? ?? ???? ?? ???? ???? ??
server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mariadb://localhost:3306/restful
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
#swagger ??? ??
#Spring boot 2.6?? ??? spring.mvc.pathmatch.matching-strategy ?? ant_apth_matcher??
#path_pattern_parser? ????? ?? ?????(swagger??)? ??? ????? ??.

jpa:
  properties:
    show_sql: true
  defer-datasource-initialization: true


